// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinTrack.Models;

public partial class Balance
{
    public int Id { get; set; }

    public decimal Amount { get; set; }

    public int? IncomeId { get; set; }

    public int? ExpenseId { get; set; }

    public virtual Expense Expense { get; set; }

    public virtual Income Income { get; set; }
}