// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinTrack.Models;

public partial class Income
{
    public int Id { get; set; }

    public decimal Amount { get; set; }

    public DateTime? Date { get; set; }

    public string Description { get; set; }

    public int? TypeOfIncomeId { get; set; }

    public virtual ICollection<Balance> Balances { get; set; } = new List<Balance>();

    public virtual TypeOfIncome TypeOfIncome { get; set; }
}