// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinTrack.Models;

public partial class TypeOfExpense
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();
}